### ISSUE TITLE
How to export Custom Map

### ISSUE THREAD

**Issue by jpoblocki77** [JAGFx/ts-map#17]
I use Coast to Coast and a few other maps that are custom.  Do I export it the same way and just setup a web server on my spare pc to serve the map files or does it have to be github and if so how???

**Comment by JAGFx** [comment]
Hi and thanks for your interest on this project.

You can export the tiles with this project. But your mod may cause some crash or mistake on the generated tiles. This mod does not have been tested yet with this project.

Note, the map tiles generated are made to work with the [JAGFx/ets2-dashboard-skin project](https://github.com/JAGFx/ets2-dashboard-skin). Read the [related map section](https://github.com/JAGFx/ets2-dashboard-skin/blob/master/doc/MAP.md#custom) if you're interested.

If you want to get the tiles and serve them, yes, you can. Read the [How to section](https://github.com/JAGFx/ts-map#how-to-use-) for more information.

**Comment by jpoblocki77** [comment]
BUt how do I export them as its not a dlc its a scs file that has to be downloaded.  DO I need to do anything speical or just start the game load the maps and then exit and export?

**Comment by JAGFx** [comment]
Hi, @jpoblocki77 

This project allow you to export only your owned DLC. 
Also, you don't need to run the game to export the map tiles collection. Just follow the [How to use](https://github.com/JAGFx/ts-map#how-to-use-) section ;)
